# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d9cb2f35116fb28e541eef65545c43eea5085c7d134920af450db72c20a95815b95c74a42a72e308726fe00c8d7ab469b18bc98eaa2639b84bc2cf63426581a

test:
  secret_key_base: e693cf11cbb6e9e980156b775edcc150e6f1ed56be99907ac015660bc079369220ae15f3cdf87a05f55b328b8e1a14089d89e7a2114bb0f6368e55daa3d6b977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
